language: node_js
node_js:
  - "0.11"
  - "0.10"
  - "0.8"
  - "0.6"
  
after_success:
  - if [[ "$TRAVIS_BRANCH" != "master" ]]; then echo "Deployments are only done for the master branch. "; exit 0; fi
  - echo "Deploying build $TRAVIS_BUILD_NUMBER"
  - bash deploy
